spring.application.name=DigitalGoldWallet
spring.profiles.active=dev
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
eureka.client.enabled=false
spring.cloud.discovery.enabled=false